"""Scaffold everything a new upstream source needs, with the names already wired up.

WHY THIS EXISTS
    Adding a source touches four files that must agree on five names. Get one wrong
    and the failure arrives late and unhelpfully: a KeyError inside a container, or a
    connection timeout that looks like the API is down. The names are mechanical, so
    a generator should own them rather than a checklist.

    What has to agree:

        registry `secret:sources.<name>.api_key`   ->  .dlt/secrets.toml path
        registry `env_var: SOURCES__<NAME>__API_KEY` -> the same path, uppercased,
                                                        dots doubled to underscores
        registry `secret: DLT_DB.OPS.<NAME>_API_KEY` -> CREATE SECRET in 03_secrets
        registry `external_access: <NAME>_API_EAI`   -> the EAI in 02_external_access
        registry `database: <NAME>`                  -> the databases in 01_databases

USAGE
    make new-source NAME=weather HOST=api.weather.example
    python tools/new_source.py weather --host api.weather.example

WHAT IT WRITES
    sql/sources/<name>/01_databases.sql          <NAME>_DEV_DB and <NAME>_PROD_DB
    sql/sources/<name>/02_external_access.sql    network rule + EAI for HOST
    sql/sources/<name>/03_secrets.sql            the API-key secret and its grants
    sql/sources/<name>/05_dbt_trigger.sql        stream -> triggered task -> dbt build
    pipelines/batch/registries/<name>-registry.yml  a one-resource starting point

    Nothing is applied and nothing existing is overwritten. The generated files are a
    starting point to edit, not a finished integration: the registry stub declares one
    resource against a placeholder path, because pagination, auth shape and merge keys
    cannot be guessed.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

DATABASES_SQL = '''\
-- =============================================================================
-- sources/{name}/01_databases.sql
-- Purpose : Storage for ONE source: {upper}_DEV_DB (per-developer sandboxes) and
--           {upper}_PROD_DB (scheduled loads into RAW, dbt models into ANALYTICS).
-- Run as  : SYSADMIN (owns the databases and issues the grants below).
-- Prerequisites : base/01_roles.sql, base/02_control_plane.sql.
-- Apply   : make setup-source SOURCE={name} CONFIRM=1
--
-- Generated by tools/new_source.py. Edit freely.
--
-- WHY ONE DATABASE PER SOURCE PER ENVIRONMENT
--   The database is the axis Snowflake makes cheapest to grant, clone, replicate and
--   drop. Crossing it with environment makes the dev/prod boundary structural rather
--   than conventional: DLT_DEV_ROLE holds no grant on {upper}_PROD_DB at all, so a
--   mis-set dataset in a dev run cannot reach production data.
-- =============================================================================

USE ROLE SYSADMIN;

-- ---------------------------------------------------------------------------
-- 1. Development database
-- ---------------------------------------------------------------------------

CREATE DATABASE IF NOT EXISTS {upper}_DEV_DB
    COMMENT = '{name} development data. Per-developer schemas (DEV_<user>), created on demand.';

CREATE SCHEMA IF NOT EXISTS {upper}_DEV_DB.OPS
    COMMENT = '{name} development run metadata: _DLT_RUNS.';

GRANT USAGE         ON DATABASE {upper}_DEV_DB TO ROLE DLT_DEV_ROLE;

-- CREATE SCHEMA is what lets dlt create DEV_<user> and its _STAGING sibling on the
-- first run. Schemas it creates are owned by this role, so tables inside them need
-- no further grant.
GRANT CREATE SCHEMA ON DATABASE {upper}_DEV_DB TO ROLE DLT_DEV_ROLE;

GRANT USAGE         ON SCHEMA {upper}_DEV_DB.OPS TO ROLE DLT_DEV_ROLE;
GRANT CREATE TABLE  ON SCHEMA {upper}_DEV_DB.OPS TO ROLE DLT_DEV_ROLE;
GRANT CREATE VIEW   ON SCHEMA {upper}_DEV_DB.OPS TO ROLE DLT_DEV_ROLE;
GRANT CREATE STAGE  ON SCHEMA {upper}_DEV_DB.OPS TO ROLE DLT_DEV_ROLE;

-- ---------------------------------------------------------------------------
-- 2. Production database
-- ---------------------------------------------------------------------------

CREATE DATABASE IF NOT EXISTS {upper}_PROD_DB
    COMMENT = '{name} production data. Scheduled dlt loads into RAW; dbt builds ANALYTICS.';

CREATE SCHEMA IF NOT EXISTS {upper}_PROD_DB.RAW
    COMMENT = 'Raw / landing layer written by dlt (production).';

-- NOT called STAGING, deliberately: dlt creates <dataset>_STAGING for every merge, so
-- RAW_STAGING already exists here and a dbt schema called STAGING would sit beside it
-- meaning something entirely different.
CREATE SCHEMA IF NOT EXISTS {upper}_PROD_DB.ANALYTICS
    COMMENT = 'dbt models built on RAW. Not STAGING: dlt owns RAW_STAGING.';

CREATE SCHEMA IF NOT EXISTS {upper}_PROD_DB.OPS
    COMMENT = '{name} production run metadata: _DLT_RUNS.';

GRANT USAGE ON DATABASE {upper}_PROD_DB TO ROLE DLT_LOADER_ROLE;

-- Required: dlt creates <dataset>_STAGING for every merge-disposition load, so
-- without this the first scheduled run fails trying to create RAW_STAGING.
GRANT CREATE SCHEMA ON DATABASE {upper}_PROD_DB TO ROLE DLT_LOADER_ROLE;

GRANT USAGE        ON SCHEMA {upper}_PROD_DB.RAW TO ROLE DLT_LOADER_ROLE;
GRANT CREATE TABLE ON SCHEMA {upper}_PROD_DB.RAW TO ROLE DLT_LOADER_ROLE;
GRANT CREATE VIEW  ON SCHEMA {upper}_PROD_DB.RAW TO ROLE DLT_LOADER_ROLE;
GRANT CREATE STAGE ON SCHEMA {upper}_PROD_DB.RAW TO ROLE DLT_LOADER_ROLE;

GRANT USAGE        ON SCHEMA {upper}_PROD_DB.OPS TO ROLE DLT_LOADER_ROLE;
GRANT CREATE TABLE ON SCHEMA {upper}_PROD_DB.OPS TO ROLE DLT_LOADER_ROLE;
GRANT CREATE VIEW  ON SCHEMA {upper}_PROD_DB.OPS TO ROLE DLT_LOADER_ROLE;
GRANT CREATE STAGE ON SCHEMA {upper}_PROD_DB.OPS TO ROLE DLT_LOADER_ROLE;

GRANT USAGE ON SCHEMA {upper}_PROD_DB.ANALYTICS TO ROLE DLT_LOADER_ROLE;

-- ---------------------------------------------------------------------------
-- 3. What is deliberately NOT granted
--
-- DLT_DEV_ROLE gets nothing on {upper}_PROD_DB, and DLT_LOADER_ROLE gets nothing on
-- {upper}_DEV_DB. The separation is a missing grant on a different database, not a
-- convention about schema names, so no run-time mistake can cross it.
-- ---------------------------------------------------------------------------
'''

EAI_SQL = '''\
-- =============================================================================
-- sources/{name}/02_external_access.sql
-- Purpose : Let SPCS jobs reach the {name} API. A container has NO network egress
--           by default, so every rest_api pipeline needs this, in dev AND in prod.
-- Run as  : ACCOUNTADMIN (network rule + integration), then grant usage.
-- Apply   : make setup-source SOURCE={name} CONFIRM=1
--
-- Generated by tools/new_source.py.
--
-- THE PORT IS REQUIRED in VALUE_LIST; a bare hostname is not enough. List every host
-- the source touches, including any auth or CDN host it redirects to. A missing host
-- shows up as a connection timeout, which reads like the API being down.
-- =============================================================================

USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE NETWORK RULE DLT_DB.OPS.{upper}_API_EGRESS
    MODE       = EGRESS
    TYPE       = HOST_PORT
    VALUE_LIST = ('{host}:443')
    COMMENT    = 'HTTPS egress for the {name} rest_api source.';

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION {upper}_API_EAI
    ALLOWED_NETWORK_RULES = (DLT_DB.OPS.{upper}_API_EGRESS)
    ENABLED = TRUE
    COMMENT = 'External access for dlt SPCS jobs loading the {name} API.';

-- Both roles create SPCS jobs: DLT_DEV_ROLE via `make run-spcs`, DLT_LOADER_ROLE via
-- the scheduled Tasks. The registry entry names this integration in its
-- `external_access` field, and generate_tasks.py emits it into the Task DDL.
GRANT USAGE ON INTEGRATION {upper}_API_EAI TO ROLE DLT_DEV_ROLE;
GRANT USAGE ON INTEGRATION {upper}_API_EAI TO ROLE DLT_LOADER_ROLE;
'''

SECRETS_SQL = '''\
-- =============================================================================
-- sources/{name}/03_secrets.sql
-- Purpose : The Snowflake SECRET an SPCS job mounts as an environment variable,
--           keeping the API token out of the image and out of git.
-- Run as  : SYSADMIN (owns DLT_DB.OPS).
-- Apply   : make setup-source SOURCE={name} CONFIRM=1
--
-- Generated by tools/new_source.py.
--
-- HOW THE NAMES CONNECT. The container binds this secret to an env var, and dlt
-- resolves a `secret:<dotted.path>` value in the registry from that env var by
-- uppercasing the path and replacing dots with double underscores:
--
--     registry config : api_key: "secret:sources.{name}.api_key"
--     env var         : SOURCES__{upper}__API_KEY
--     registry fields : secret: DLT_DB.OPS.{upper}_API_KEY
--                       env_var: SOURCES__{upper}__API_KEY
--
-- All four are already wired in the generated registry stub. Change one and change
-- all of them, or the container raises KeyError from dlt.secrets.
-- =============================================================================

USE ROLE SYSADMIN;

-- THIS DOES NOT SET A USABLE KEY, AND CANNOT.
--
-- `IF NOT EXISTS` makes the statement a no-op after the first run, so whatever value
-- it writes is pinned until somebody runs the ALTER below. Re-applying this file does
-- not fix a wrong key; it silently does nothing. The object still has to be created
-- here because the GRANTs need it to exist.
CREATE SECRET IF NOT EXISTS DLT_DB.OPS.{upper}_API_KEY
    TYPE          = GENERIC_STRING
    SECRET_STRING = 'UNSET-RUN-THE-ALTER-BELOW'
    COMMENT       = 'API key for the {name} rest_api source. Set via ALTER.';

-- REQUIRED on every account this is applied to. Nothing that touches the API works
-- until it runs:
--
--     ALTER SECRET DLT_DB.OPS.{upper}_API_KEY SET SECRET_STRING = '<the real key>';
--
-- A secret cannot be read back, so no query proves it is right. The only test is a
-- run.
--
-- READ, not just USAGE. Mounting a secret into a container reads its value, which
-- needs READ; USAGE only permits referencing it. Granting USAGE alone fails at
-- EXECUTE JOB SERVICE time with "does not exist or not authorized", which reads like
-- a typo in the name rather than a missing grant.
GRANT READ  ON SECRET DLT_DB.OPS.{upper}_API_KEY TO ROLE DLT_DEV_ROLE;
GRANT READ  ON SECRET DLT_DB.OPS.{upper}_API_KEY TO ROLE DLT_LOADER_ROLE;
GRANT USAGE ON SECRET DLT_DB.OPS.{upper}_API_KEY TO ROLE DLT_DEV_ROLE;
GRANT USAGE ON SECRET DLT_DB.OPS.{upper}_API_KEY TO ROLE DLT_LOADER_ROLE;
'''

REGISTRY_YML = '''\
# {name} pipelines. Generated by tools/new_source.py; edit freely.
#
# Every file in registries/ is merged into ONE registry, so pipeline names must be
# unique across all of them. `defaults:` applies only to this file's pipelines.
#
# SECRETS ARE NEVER STORED HERE. `secret:<path>` points at a key in
# .dlt/secrets.toml locally, or at a Snowflake SECRET bound to an env var in SPCS.
# For local runs, add to .dlt/secrets.toml:
#
#     [sources.{name}]
#     api_key = "..."

anchors:
  {name}_client: &{name}_client
    base_url: "https://{host}/"
    auth:
      # TODO: check the auth shape your API wants. This is a raw key in an
      # Authorization header with no scheme prefix. If yours expects "Bearer <key>",
      # use `auth: {{token: ...}}` instead.
      type: api_key
      name: Authorization
      location: header
      api_key: "secret:sources.{name}.api_key"
    # TODO: `single_page` is the safe default. Override per resource for paginated
    # endpoints (cursor, offset, json_link).
    paginator: single_page

defaults:
  destination: snowflake
  database: {upper}          # -> {upper}_DEV_DB / {upper}_PROD_DB
  dataset_name: RAW          # target schema inside that database
  group: {name}              # make run-local GROUP={name}
  load_warehouse: DLT_WH
  compute_pool: DLT_POOL
  # Read by `make run-spcs` in dev and by generate_tasks.py in prod, so the binding
  # is recorded once. These names match sql/sources/{name}/.
  secret: DLT_DB.OPS.{upper}_API_KEY
  env_var: SOURCES__{upper}__API_KEY
  external_access: {upper}_API_EAI

pipelines:
  # A starting point, not a finished integration. Replace the path, add a primary_key
  # once you know what identifies a row, and set the paginator your API needs.
  #
  # NO `schedule:` yet, deliberately. Add one only after a manual run works:
  # `make run-spcs NAME={name}_example`. A pipeline with a schedule must also carry
  # secret, env_var and external_access, which the defaults above already provide.
  - name: {name}_example
    source: rest_api
    config:
      client: *{name}_client
      resource_defaults:
        endpoint:
          # Rows usually live under a key like `data`. Without this the whole
          # response envelope loads as a single row.
          data_selector: data
      resources:
        - name: example
          # TODO: `merge` needs a primary_key or dlt silently APPENDS, duplicating
          # every row on every run. Use `replace` for a small full snapshot instead.
          write_disposition: replace
          endpoint:
            # `path` does NOT inherit from resource_defaults; declare it per resource
            # or dlt uses the resource NAME as the path and you get a 404.
            path: TODO_endpoint
'''


DBT_TRIGGER_SQL = """\
-- =============================================================================
-- 05_dbt_trigger.sql ({name}) -- event-driven dbt build after ingestion
-- =============================================================================
-- Chain: dlt load succeeds -> one INSERT lands in RAW._DLT_LOADS -> the
-- append-only stream below has data -> the triggered task fires (no schedule;
-- idle costs nothing) -> the procedure drains the stream into an audit table
-- and runs EXECUTE DBT PROJECT for this sport. A FAILED load never inserts
-- into _DLT_LOADS, so failures never trigger a rebuild, structurally.
--
-- Conventions this file obeys (verified in WORKFLOW-4.md Phase 0):
--   * The task name avoids the DLT_TASK_ prefix: DLT_DB.OPS.V_TASK_RUNS turns
--     anything matching it into a pipeline row (see sql/ops/05_retention.sql
--     for the original warning). Living in <SPORT>_PROD_DB.OPS also keeps it
--     out of that view's DLT_DB filter entirely.
--   * This task is NOT managed by generate_tasks.py: make tasks-suspend /
--     tasks-apply / tasks-resume do not touch it. Suspend-before-alter is
--     built into this file instead, and the RESUME at the bottom is not
--     redundant: CREATE OR ALTER TASK leaves a task suspended.
--   * The DML drain in the procedure is mandatory, not an audit nicety: a
--     stream that is only read keeps SYSTEM$STREAM_HAS_DATA true and the task
--     re-fires every interval forever, billing DBT_WH (measured: 4 fires in
--     90 seconds). Drain-first also means a load landing mid-build simply
--     re-triggers after this one finishes.
--   * ENVIRONMENT is explicit because the project objects default to dev;
--     omitting it silently builds the wrong environment.
--   * A partial dbt failure raises a real SQL error (verified), so failures
--     land in TASK_HISTORY with ERROR_MESSAGE and count toward
--     SUSPEND_TASK_AFTER_NUM_FAILURES. No result inspection is needed.
--   * The 900s trigger interval coalesces: a burst of loads inside the window
--     produces one build that drains all of them (verified with 3 inserts ->
--     1 run). Evaluations that find no data are SKIPPED at zero cost.
--
-- Kill switch:  ALTER TASK {upper}_PROD_DB.OPS.DBT_BUILD_{upper} SUSPEND;
-- (ingestion untouched; the stream accumulates and is drained on resume;
-- staleness grace ~14 days, re-create the stream if suspended longer, and
-- also if dlt ever recreates _DLT_LOADS itself.)
--
-- History: SNOWFLAKE.ACCOUNT_USAGE.DBT_PROJECT_EXECUTION_HISTORY plus
-- TASK_HISTORY in this database. Not visible in V_TASK_RUNS, by design.
--
-- ORDER PREREQUISITE: the GRANT ON DBT PROJECT below needs the project
-- object to exist, so on a fresh account run
-- make -C ../dbt-pipelines deploy-sport SPORT={name} BEFORE this file.
--
-- Apply with make setup-source SOURCE={name} CONFIRM=1.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Section 1: grants and ownership (idempotent; roles from sql/base/04)
-- -----------------------------------------------------------------------------

USE ROLE SYSADMIN;

GRANT USAGE ON DATABASE {upper}_PROD_DB TO ROLE DBT_RUNNER_ROLE;
GRANT USAGE ON SCHEMA {upper}_PROD_DB.RAW TO ROLE DBT_RUNNER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA {upper}_PROD_DB.RAW TO ROLE DBT_RUNNER_ROLE;

-- USAGE is load-bearing beyond navigation: a task cannot run if its owner
-- role lacks USAGE on the task's schema (verified the hard way in Phase 0).
GRANT USAGE, CREATE STREAM, CREATE TABLE, CREATE PROCEDURE, CREATE TASK
  ON SCHEMA {upper}_PROD_DB.OPS TO ROLE DBT_RUNNER_ROLE;

-- The invoke privilege for EXECUTE DBT PROJECT is USAGE on the object
-- (verified; the docs disagree with themselves). Object created by
-- make -C ../dbt-pipelines deploy-sport SPORT={name}.
GRANT USAGE ON DBT PROJECT DLT_DB.DEPLOY.CORTEX_LIFECYCLE_{upper} TO ROLE DBT_RUNNER_ROLE;

USE ROLE DLT_LOADER_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA {upper}_PROD_DB.RAW TO ROLE DBT_RUNNER_ROLE;

-- Streams need change tracking on the source table, and creating a stream as
-- a non-owner does not enable it. Explicit, as the table owner.
ALTER TABLE {upper}_PROD_DB.RAW._DLT_LOADS SET CHANGE_TRACKING = TRUE;

USE ROLE SYSADMIN;

-- Ownership transfer, not broad grants: dbt materializes with CREATE OR
-- REPLACE, which requires owning the existing object. SYSADMIN keeps full
-- access through the role hierarchy. Semantic views are their own object
-- class with their own bulk-transfer form (verified). Agents in ANALYTICS
-- stay SYSADMIN-owned: dbt does not manage them.
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA {upper}_PROD_DB.PREP TO ROLE DBT_RUNNER_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA {upper}_PROD_DB.PREP TO ROLE DBT_RUNNER_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA {upper}_PROD_DB.PREP TO ROLE DBT_RUNNER_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA {upper}_PROD_DB.CORE TO ROLE DBT_RUNNER_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA {upper}_PROD_DB.CORE TO ROLE DBT_RUNNER_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA {upper}_PROD_DB.CORE TO ROLE DBT_RUNNER_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA {upper}_PROD_DB.ANALYTICS TO ROLE DBT_RUNNER_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA {upper}_PROD_DB.ANALYTICS TO ROLE DBT_RUNNER_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SEMANTIC VIEWS IN SCHEMA {upper}_PROD_DB.ANALYTICS TO ROLE DBT_RUNNER_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA {upper}_PROD_DB.ANALYTICS TO ROLE DBT_RUNNER_ROLE COPY CURRENT GRANTS;

-- -----------------------------------------------------------------------------
-- Section 2: the trigger machinery, owned by DBT_RUNNER_ROLE
-- -----------------------------------------------------------------------------

USE ROLE DBT_RUNNER_ROLE;

CREATE STREAM IF NOT EXISTS {upper}_PROD_DB.OPS.DBT_LOADS_STREAM
  ON TABLE {upper}_PROD_DB.RAW._DLT_LOADS APPEND_ONLY = TRUE
  COMMENT = 'One row per successful dlt load; consumed only by DBT_BUILD_{upper} (one stream per consumer).';

CREATE TABLE IF NOT EXISTS {upper}_PROD_DB.OPS.DBT_TRIGGER_LOADS (
  LOAD_ID             VARCHAR,
  PIPELINE            VARCHAR,
  STATUS              NUMBER,
  INSERTED_AT         TIMESTAMP_NTZ,
  DRAINED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Audit: which loads triggered which dbt build. The INSERT that fills this is also the stream consumption that stops re-triggering.';

CREATE OR REPLACE PROCEDURE {upper}_PROD_DB.OPS.SP_DBT_BUILD()
RETURNS VARCHAR
LANGUAGE SQL
COMMENT = 'Drain DBT_LOADS_STREAM, then dbt build for {upper}. Caller''s rights: EXECUTE DBT PROJECT requires it.'
EXECUTE AS CALLER
AS
$$
DECLARE
  drained INTEGER;
BEGIN
  -- Drain FIRST. This is the stream consumption; without it the task
  -- re-fires every interval forever.
  INSERT INTO {upper}_PROD_DB.OPS.DBT_TRIGGER_LOADS (LOAD_ID, PIPELINE, STATUS, INSERTED_AT, DRAINED_AT)
    SELECT LOAD_ID, SCHEMA_NAME, STATUS, INSERTED_AT, CURRENT_TIMESTAMP()
    FROM {upper}_PROD_DB.OPS.DBT_LOADS_STREAM;
  drained := SQLROWCOUNT;

  -- SYSTEM$STREAM_HAS_DATA tolerates false positives; do not build on one.
  IF (drained = 0) THEN
    RETURN 'no-op: stream was empty';
  END IF;

  -- Explicit ENVIRONMENT: the project object defaults to dev. A partial dbt
  -- failure raises here, failing the task with the message in TASK_HISTORY.
  EXECUTE DBT PROJECT DLT_DB.DEPLOY.CORTEX_LIFECYCLE_{upper}
    ARGS = 'build'
    ENVIRONMENT = '{name}_prod';

  RETURN 'built after ' || drained || ' load(s)';
END;
$$;

-- CREATE OR ALTER TASK refuses to touch a started task; suspend first.
ALTER TASK IF EXISTS {upper}_PROD_DB.OPS.DBT_BUILD_{upper} SUSPEND;

CREATE OR ALTER TASK {upper}_PROD_DB.OPS.DBT_BUILD_{upper}
  WAREHOUSE = DBT_WH
  USER_TASK_MINIMUM_TRIGGER_INTERVAL_IN_SECONDS = 900
  USER_TASK_TIMEOUT_MS = 3600000
  COMMENT = 'dbt build for {upper} on new RAW loads. NOT managed by generate_tasks.py; history in SNOWFLAKE.ACCOUNT_USAGE.DBT_PROJECT_EXECUTION_HISTORY.'
  WHEN SYSTEM$STREAM_HAS_DATA('{upper}_PROD_DB.OPS.DBT_LOADS_STREAM')
AS
  CALL {upper}_PROD_DB.OPS.SP_DBT_BUILD();

-- Not redundant: CREATE OR ALTER TASK leaves the task suspended.
ALTER TASK {upper}_PROD_DB.OPS.DBT_BUILD_{upper} RESUME;
"""


def _slug(value: str) -> str:
    """Validate a source name: it becomes a database prefix and a SQL identifier."""
    name = value.strip().lower()
    if not re.fullmatch(r"[a-z][a-z0-9_]*", name):
        raise SystemExit(
            f"invalid source name {value!r}: use letters, digits and underscores, "
            "starting with a letter (it becomes a database prefix)"
        )
    return name


def _write(path: Path, content: str, force: bool, root: Path) -> str:
    if path.exists() and not force:
        return f"  skipped (exists)  {path.relative_to(root)}"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return f"  wrote             {path.relative_to(root)}"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python tools/new_source.py",
        description="Scaffold the SQL and registry entry for a new upstream source.",
    )
    parser.add_argument("name", help="short source name, e.g. weather")
    parser.add_argument(
        "--host",
        default="api.example.com",
        help="API hostname for the network rule and base_url (no scheme, no port)",
    )
    parser.add_argument(
        "--force", action="store_true", help="overwrite files that already exist"
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=ROOT,
        help="repo root to write into (tests render into a temp directory)",
    )
    args = parser.parse_args(argv)

    name = _slug(args.name)
    fields = {"name": name, "upper": name.upper(), "host": args.host}

    root = args.out_dir
    sql_dir = root / "sql" / "sources" / name
    results = [
        _write(sql_dir / "01_databases.sql", DATABASES_SQL.format(**fields), args.force, root),
        _write(sql_dir / "02_external_access.sql", EAI_SQL.format(**fields), args.force, root),
        _write(sql_dir / "03_secrets.sql", SECRETS_SQL.format(**fields), args.force, root),
        _write(
            sql_dir / "05_dbt_trigger.sql", DBT_TRIGGER_SQL.format(**fields), args.force, root
        ),
        _write(
            root / "pipelines" / "batch" / "registries" / f"{name}-registry.yml",
            REGISTRY_YML.format(**fields),
            args.force,
            root,
        ),
    ]
    print("\n".join(results))

    print(
        f"""
Next, in order:

  1. Edit pipelines/batch/registries/{name}-registry.yml
       the endpoint path, the paginator, and a primary_key if the resource merges.
  2. Edit sql/sources/{name}/02_external_access.sql if the API touches more hosts
       than {args.host}.
  3. make setup-source SOURCE={name} CONFIRM=1
  4. Set the real key, which no DDL can do for you:
       ALTER SECRET DLT_DB.OPS.{name.upper()}_API_KEY SET SECRET_STRING = '<key>';
  5. make run-local NAME={name}_example      (needs .dlt/secrets.toml, no Snowflake)
  6. make sync-apply && make run-spcs NAME={name}_example

Add a `schedule:` only once step 6 works. `make test` rejects a schedule without the
secret, env_var and external_access bindings, which the stub already sets.

dbt, once models exist for the sport (see WORKFLOW-3/4 for the pattern):
  a. dbt-pipelines/env.yml: add {name}_dev / {name}_prod environments
       (DBT_SPORT: {name}, prod uses DBT_RUNNER_ROLE on DBT_WH).
  b. dbt-pipelines/dbt_project.yml: add the models/{name} sibling config key.
  c. make -C ../dbt-pipelines deploy-sport SPORT={name}
       (creates DLT_DB.DEPLOY.CORTEX_LIFECYCLE_{name.upper()}; must exist BEFORE
       the next step's GRANT ON DBT PROJECT can succeed).
  d. Re-run make setup-source SOURCE={name} CONFIRM=1 to apply
       sql/sources/{name}/05_dbt_trigger.sql: after that, every successful
       load triggers the sport's dbt build automatically.
"""
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
