-- =============================================================================
-- sources/ncaaf/02_external_access.sql
-- Purpose : Let SPCS jobs reach the ncaaf API. A container has NO network egress
--           by default, so every rest_api pipeline needs this, in dev AND in prod.
-- Run as  : ACCOUNTADMIN (network rule + integration), then grant usage.
-- Apply   : make setup-source SOURCE=ncaaf CONFIRM=1
--
-- Generated by tools/new_source.py.
--
-- THE PORT IS REQUIRED in VALUE_LIST; a bare hostname is not enough. List every host
-- the source touches, including any auth or CDN host it redirects to. A missing host
-- shows up as a connection timeout, which reads like the API being down.
-- =============================================================================

USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE NETWORK RULE DLT_DB.OPS.NCAAF_API_EGRESS
    MODE       = EGRESS
    TYPE       = HOST_PORT
    VALUE_LIST = ('api.balldontlie.io:443')
    COMMENT    = 'HTTPS egress for the ncaaf rest_api source.';

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION NCAAF_API_EAI
    ALLOWED_NETWORK_RULES = (DLT_DB.OPS.NCAAF_API_EGRESS)
    ENABLED = TRUE
    COMMENT = 'External access for dlt SPCS jobs loading the ncaaf API.';

-- Both roles create SPCS jobs: DLT_DEV_ROLE via `make run-spcs`, DLT_LOADER_ROLE via
-- the scheduled Tasks. The registry entry names this integration in its
-- `external_access` field, and generate_tasks.py emits it into the Task DDL.
GRANT USAGE ON INTEGRATION NCAAF_API_EAI TO ROLE DLT_DEV_ROLE;
GRANT USAGE ON INTEGRATION NCAAF_API_EAI TO ROLE DLT_LOADER_ROLE;
