-- =============================================================================
-- sources/ncaaf/03_secrets.sql
-- Purpose : The Snowflake SECRET an SPCS job mounts as an environment variable,
--           keeping the API token out of the image and out of git.
-- Run as  : SYSADMIN (owns DLT_DB.OPS).
-- Apply   : make setup-source SOURCE=ncaaf CONFIRM=1
--
-- Generated by tools/new_source.py.
--
-- HOW THE NAMES CONNECT. The container binds this secret to an env var, and dlt
-- resolves a `secret:<dotted.path>` value in the registry from that env var by
-- uppercasing the path and replacing dots with double underscores:
--
--     registry config : api_key: "secret:sources.ncaaf.api_key"
--     env var         : SOURCES__NCAAF__API_KEY
--     registry fields : secret: DLT_DB.OPS.NCAAF_API_KEY
--                       env_var: SOURCES__NCAAF__API_KEY
--
-- All four are already wired in the generated registry stub. Change one and change
-- all of them, or the container raises KeyError from dlt.secrets.
-- =============================================================================

USE ROLE SYSADMIN;

-- THIS DOES NOT SET A USABLE KEY, AND CANNOT.
--
-- `IF NOT EXISTS` makes the statement a no-op after the first run, so whatever value
-- it writes is pinned until somebody runs the ALTER below. Re-applying this file does
-- not fix a wrong key; it silently does nothing. The object still has to be created
-- here because the GRANTs need it to exist.
CREATE SECRET IF NOT EXISTS DLT_DB.OPS.NCAAF_API_KEY
    TYPE          = GENERIC_STRING
    SECRET_STRING = 'UNSET-RUN-THE-ALTER-BELOW'
    COMMENT       = 'API key for the ncaaf rest_api source. Set via ALTER.';

-- REQUIRED on every account this is applied to. Nothing that touches the API works
-- until it runs:
--
--     ALTER SECRET DLT_DB.OPS.NCAAF_API_KEY SET SECRET_STRING = '<the real key>';
--
-- A secret cannot be read back, so no query proves it is right. The only test is a
-- run.
--
-- READ, not just USAGE. Mounting a secret into a container reads its value, which
-- needs READ; USAGE only permits referencing it. Granting USAGE alone fails at
-- EXECUTE JOB SERVICE time with "does not exist or not authorized", which reads like
-- a typo in the name rather than a missing grant.
GRANT READ  ON SECRET DLT_DB.OPS.NCAAF_API_KEY TO ROLE DLT_DEV_ROLE;
GRANT READ  ON SECRET DLT_DB.OPS.NCAAF_API_KEY TO ROLE DLT_LOADER_ROLE;
GRANT USAGE ON SECRET DLT_DB.OPS.NCAAF_API_KEY TO ROLE DLT_DEV_ROLE;
GRANT USAGE ON SECRET DLT_DB.OPS.NCAAF_API_KEY TO ROLE DLT_LOADER_ROLE;
