-- =============================================================================
-- sources/wnba/01_databases.sql
-- Purpose : Storage for ONE source: WNBA_DEV_DB (per-developer sandboxes) and
--           WNBA_PROD_DB (scheduled loads into RAW, dbt models into ANALYTICS).
-- Run as  : SYSADMIN (owns the databases and issues the grants below).
-- Prerequisites : base/01_roles.sql, base/02_control_plane.sql.
-- Apply   : make setup-source SOURCE=wnba CONFIRM=1
--
-- Generated by tools/new_source.py. Edit freely.
--
-- WHY ONE DATABASE PER SOURCE PER ENVIRONMENT
--   The database is the axis Snowflake makes cheapest to grant, clone, replicate and
--   drop. Crossing it with environment makes the dev/prod boundary structural rather
--   than conventional: DLT_DEV_ROLE holds no grant on WNBA_PROD_DB at all, so a
--   mis-set dataset in a dev run cannot reach production data.
-- =============================================================================

USE ROLE SYSADMIN;

-- ---------------------------------------------------------------------------
-- 1. Development database
-- ---------------------------------------------------------------------------

CREATE DATABASE IF NOT EXISTS WNBA_DEV_DB
    COMMENT = 'wnba development data. Per-developer schemas (DEV_<user>), created on demand.';

CREATE SCHEMA IF NOT EXISTS WNBA_DEV_DB.OPS
    COMMENT = 'wnba development run metadata: _DLT_RUNS.';

GRANT USAGE         ON DATABASE WNBA_DEV_DB TO ROLE DLT_DEV_ROLE;

-- CREATE SCHEMA is what lets dlt create DEV_<user> and its _STAGING sibling on the
-- first run. Schemas it creates are owned by this role, so tables inside them need
-- no further grant.
GRANT CREATE SCHEMA ON DATABASE WNBA_DEV_DB TO ROLE DLT_DEV_ROLE;

GRANT USAGE         ON SCHEMA WNBA_DEV_DB.OPS TO ROLE DLT_DEV_ROLE;
GRANT CREATE TABLE  ON SCHEMA WNBA_DEV_DB.OPS TO ROLE DLT_DEV_ROLE;
GRANT CREATE VIEW   ON SCHEMA WNBA_DEV_DB.OPS TO ROLE DLT_DEV_ROLE;
GRANT CREATE STAGE  ON SCHEMA WNBA_DEV_DB.OPS TO ROLE DLT_DEV_ROLE;

-- ---------------------------------------------------------------------------
-- 2. Production database
-- ---------------------------------------------------------------------------

CREATE DATABASE IF NOT EXISTS WNBA_PROD_DB
    COMMENT = 'wnba production data. Scheduled dlt loads into RAW; dbt builds ANALYTICS.';

CREATE SCHEMA IF NOT EXISTS WNBA_PROD_DB.RAW
    COMMENT = 'Raw / landing layer written by dlt (production).';

-- NOT called STAGING, deliberately: dlt creates <dataset>_STAGING for every merge, so
-- RAW_STAGING already exists here and a dbt schema called STAGING would sit beside it
-- meaning something entirely different.
CREATE SCHEMA IF NOT EXISTS WNBA_PROD_DB.ANALYTICS
    COMMENT = 'dbt models built on RAW. Not STAGING: dlt owns RAW_STAGING.';

CREATE SCHEMA IF NOT EXISTS WNBA_PROD_DB.OPS
    COMMENT = 'wnba production run metadata: _DLT_RUNS.';

GRANT USAGE ON DATABASE WNBA_PROD_DB TO ROLE DLT_LOADER_ROLE;

-- Required: dlt creates <dataset>_STAGING for every merge-disposition load, so
-- without this the first scheduled run fails trying to create RAW_STAGING.
GRANT CREATE SCHEMA ON DATABASE WNBA_PROD_DB TO ROLE DLT_LOADER_ROLE;

GRANT USAGE        ON SCHEMA WNBA_PROD_DB.RAW TO ROLE DLT_LOADER_ROLE;
GRANT CREATE TABLE ON SCHEMA WNBA_PROD_DB.RAW TO ROLE DLT_LOADER_ROLE;
GRANT CREATE VIEW  ON SCHEMA WNBA_PROD_DB.RAW TO ROLE DLT_LOADER_ROLE;
GRANT CREATE STAGE ON SCHEMA WNBA_PROD_DB.RAW TO ROLE DLT_LOADER_ROLE;

GRANT USAGE        ON SCHEMA WNBA_PROD_DB.OPS TO ROLE DLT_LOADER_ROLE;
GRANT CREATE TABLE ON SCHEMA WNBA_PROD_DB.OPS TO ROLE DLT_LOADER_ROLE;
GRANT CREATE VIEW  ON SCHEMA WNBA_PROD_DB.OPS TO ROLE DLT_LOADER_ROLE;
GRANT CREATE STAGE ON SCHEMA WNBA_PROD_DB.OPS TO ROLE DLT_LOADER_ROLE;

GRANT USAGE ON SCHEMA WNBA_PROD_DB.ANALYTICS TO ROLE DLT_LOADER_ROLE;

-- ---------------------------------------------------------------------------
-- 3. What is deliberately NOT granted
--
-- DLT_DEV_ROLE gets nothing on WNBA_PROD_DB, and DLT_LOADER_ROLE gets nothing on
-- WNBA_DEV_DB. The separation is a missing grant on a different database, not a
-- convention about schema names, so no run-time mistake can cross it.
-- ---------------------------------------------------------------------------
